USE ETRS;

INSERT INTO passage_set(`id`) VALUES
(1);

INSERT INTO `passage` (`id`, `content`, `set_id`, `creation_time`) VALUES
(1, 'An object remains in a state of rest or of uniform <a href="javascript:ref(1)">motion</a> in a straight line unless compelled to change that state by an applied force. In other words, all objects resist a change in their state of motion. In a qualitative way, the tendency of undisturbed objects to stay at rest or to keep moving with the same <a href="javascript:ref(2)">velocity</a> is called inertia. This is why, the <a href="javascript:ref(3)">first law of motion</a> is also known as the law of <a href="javascript:ref(4)">inertia</a>. Certain experiences that we come across while travelling in a motorcar can be explained on the basis of the law of inertia. We tend to remain at rest with respect to the seat until the driver applies a braking force to stop the motorcar. With the application of brakes, the car slows down but our body tends to continue in the same state of motion because of its inertia. A sudden application of brakes may thus cause injury to us by impact or collision with the panels in front.\r\n', 1, '2015-01-22 17:29:36'),
(2, 'A <a href="javascript:ref(5)">wave</a> is a disturbance that moves through a <a href="javascript:ref(6)">medium</a> when the particles of the medium set neighbouring particles into motion. They in turn produce similar motion in others. The particles of the medium do not move forward themselves, but the disturbance is carried forward. This is what happens during propagation of sound in a medium, hence sound can be visualised as a wave. Sound waves are characterised by the motion of particles in the medium and are called <a href="javascript:ref(7)">mechanical waves</a>. Air is the most common medium through which sound travels. When a vibrating object moves forward, it pushes and compresses the air in front of it creating a region of high pressure. This region is called a <a href="javascript:ref(8)">compression</a>. This compression starts to move away from the vibrating object. When the vibrating object moves backwards, it creates a region of low pressure called <a href="javascript:ref(9)">rarefaction</a>. As the object moves back and forth rapidly, a series of compressions and rarefactions is created in the air. These make the sound wave that propagates through the medium.', 1, '2015-01-22 17:34:56'),
(3, '<a href="javascript:ref(10)">Monera</a>  do not have a defined nucleus or <a href="javascript:ref(11)">organelles</a>, nor do any of them show multi-cellular body designs. On the other hand, they show diversity based on many other characteristics. Some of them have cell walls while some do not. Of course, having or not having a cell wall has very different effects on body design here from having or not having a cell wall in multicellular organisms. The mode of nutrition of organisms in this group can be either by synthesising their own food (autotrophic) or getting it from the environment (heterotrophic). This group includes bacteria, blue-green algae or <a href="javascript:ref(12)">cyanobacteria</a>, and mycoplasma.  <a href="javascript:ref(13)">Protista</a> includes many kinds of unicellular eukaryotic organisms. Some of these organisms use appendages, such as hair-like <a href="javascript:ref(14)">cilia</a> or whip-like <a href="javascript:ref(15)">flagella</a> for moving around. Their mode of nutrition can be autotrophic or heterotrophic. Examples are unicellular algae, diatoms and protozoans.', 1, '2015-01-22 18:10:03'),
(4, 'Different species of <a href="javascript:ref(16)">microbes</a> seem to have evolved to home in on different parts of the body.  In part, this selection is connected to their point of entry. If they enter from the air via the nose, they are likely to go to the lungs. This is seen in the bacteria causing <a href="javascript:ref(17)">tuberculosis</a>. If they enter through the mouth, they can stay in the gut lining like typhoid causing bacteria. Or they can go to the liver, like the viruses that cause <a href=”="javascript:ref(18)">jaundice</a>. But this needn’t always be the case. An infection like HIV that comes into the body via the sexual organs will spread to <a href="javascript:ref(19)">lymph nodes</a> all over the body. <a href="javascript:ref(20)">Malaria-causing microbes</a>, entering through a mosquito bite, will go to the liver, and then to the red blood cells. The virus causing Japanese <a href="javascript:ref(21)">encephalitis</a>, or brain fever, will similarly enter through a mosquito bite. But it goes on to infect the brain.', 1, '2015-01-22 18:08:53'),
(5, 'The <a href="javascript:ref(22)">fossil fuels</a> like coal and petroleum contain small amounts of nitrogen and sulphur. When these fuels are burnt, nitrogen and sulphur too are burnt and this produces different <a href="javascript:ref(23)">oxides</a> of nitrogen and sulphur. Not only is the inhalation of these gases dangerous, they also dissolve in rain to give rise to <a href="javascript:ref(24)">acid rain</a>. The combustion of fossil fuels also increases the amount of suspended particles in air. These suspended particles could be unburnt carbon particles or substances called <a href="javascript:ref(25)">hydrocarbons</a>.  Presence of high levels of all these pollutants causes visibility to be lowered, especially in cold weather when water also condenses out of air. This is known as smog and is a visible indication of air pollution. Studies have shown that regularly breathing air that contains any of these substances increases the incidence of allergies, cancer and heart diseases. An increase in the content of these harmful substances in air is called air pollution.', 1, '2015-01-22 18:07:28'),
(6, 'We have observed that gases are highly compressible as compared to solids and liquids. The liquefied petroleum gas (<a href="javascript:ref(26)">LPG</a>) cylinder that we get in our home for cooking or the oxygen supplied to hospitals in cylinders is compressed gas. Compressed natural gas (<a href="javascript:ref(27)">CNG</a>) is used as fuel these days in vehicles. Due to its high compressibility, large <a href="javascript:ref(28)">volumes</a> of a gas can be compressed into a small cylinder and transported easily. We come to know of what is being cooked in the kitchen without even entering there, by the smell that reaches our nostrils. How does this smell reach us? The particles of the aroma of food mix with the particles of air spread from the kitchen, reach us and even farther away. The smell of hot cooked food reaches us in seconds; compare this with the rate of <a href="javascript:ref(29)">diffusion</a> of solids and liquids. Due to high speed of particles and large space between them, gases show the property of diffusing very fast into other gases.', 1, '2015-01-22 18:11:04'),
(7, ' The particles of a <a href="javascript:ref(30)">colloid</a> are uniformly spread throughout the solution. Due to the relatively smaller size of particles, as compared to that of a <a href="javascript:ref(31)">suspension</a>, the <a href="javascript:ref(32)">mixture</a> appears to be <a href="javascript:ref(33)">homogeneous</a>. But actually, a colloidal solution is a heterogeneous mixture, for example, milk. Because of the small size of colloidal particles, we cannot see them with naked eyes. But, these particles can easily scatter a beam of visible light. This scattering of a beam of light is called the <a href="javascript:ref(34)">Tyndall effect</a> after the name of the scientist who discovered this effect. Tyndall effect can also be observed when a fine beam of light enters a room through a small hole. This happens due to the scattering of light by the particles of dust and smoke in the air.', 1, '2015-01-22 18:11:24'),
(8, 'A few layers of cells form the basic packing of tissue. This tissue is <a href="javascript:ref(35)">parenchyma</a>, a type of permanent tissue. It consists of relatively unspecialised cells with thin cell walls. They are live cells. They are usually loosely packed, so that large spaces between cells (intercellular spaces) are found in this tissue. This tissue provides support to plants and also stores food. In some situations, it contains <a href="javascript:ref(36)">chlorophyll</a> and performs <a href="javascript:ref(37)">photosynthesis</a>, and then it is called chlorenchyma. In aquatic plants, large air cavities are present in parenchyma to give <a href="javascript:ref(38)">buoyancy</a> to the plants to help them float. Such a parenchyma type is called <a href="javascript:ref(39)">aerenchyma</a>. The parenchyma of stems and roots also stores nutrients and water. The flexibility in plants is due to another permanent tissue, <a href="javascript:ref(40)">collenchyma</a>. It allows easy bending in various parts of a plant (leaf, stem) without breaking. It also provides mechanical support to plants. We can find this tissue in leaf stalks below the epidermis. The cells of this tissue are living, elongated and irregularly thickened at the corners. There is very little intercellular space.', 1, '2015-01-22 18:11:54');

INSERT INTO `reference` (`id`, `content`, `creation_time`) VALUES
(1, 'In physics, motion is a change in position of an object with respect to time also on its reference point. Motion is typically described in terms of displacement, distance (scalar),velocity, acceleration, time and speed. Motion is observed by attaching a frame of reference to a body and measuring its change in position relative to that frame.', '2015-01-22 17:30:29'),
(2, 'Velocity is the rate of change of the displacement, the difference between the final and initial position of an object. Velocity is equivalent to a specification of its speed and direction of motion, e.g. 60 km/h to the north. Velocity is a vector physical quantity; both magnitude and direction are required to define it. The scalar absolute value (magnitude) of velocity is called "speed", a quantity that is measured in meters per second. ', '2015-01-22 17:31:18'),
(3, 'When viewed in an inertial reference frame, an object either remains at rest or continues to move at a constant velocity, unless acted upon by an external force. The first law states that if the net force (the vector sum of all forces acting on an object) is zero, then the velocity of the object is constant. Velocity is a vector quantity which expresses both the object''s speed and the direction of its motion; therefore, the statement that the object''s velocity is constant is a statement that both its speed and the direction of its motion are constant.', '2015-01-22 17:31:18'),
(4, 'Inertia is the resistance of any physical object to any change in its state of motion, including changes to its speed and direction. It is the tendency of objects to keep moving in a straight line at constant velocity. The principle of inertia is one of the fundamental principles of classical physics that are used to describe the motion of objects and how they are affected by applied forces.', '2015-01-22 17:31:41'),
(5, 'In physics, a wave is disturbance or oscillation (of a physical quantity), that travels through matter or space, accompanied by a transfer of energy. Wave motion transfers energy from one point to another, often with no permanent displacement of the particles of the medium—that is, with little or no associated mass transport. They consist, instead, of oscillations or vibrations around almost fixed locations.', '2015-01-22 17:36:38'),
(6, 'Transmission medium, in physics and telecommunications, any material substance which can propagate waves or energy.', '2015-01-22 17:36:38'),
(7, 'A mechanical wave is a wave that propagates as an oscillation of matter, and therefore transfers energy through a medium.  Mechanical waves transport energy only. This energy propagates in the same direction as the wave. No material is transported as a result of mechanical waves. Mechanical wave can be produced only in media which possess elasticity and inertia.', '2015-01-22 17:36:38'),
(8, 'In mechanics, compression is the application of balanced inward ("pushing") forces to different points on a material or structure, that is, forces with no net sum or torque directed so as to reduce its size in one or more directions. When put under compression (or any other type of stress), every material will suffer some deformation, even if imperceptible, that causes the average relative positions of its atoms and molecules to change.', '2015-01-22 17:36:38'),
(9, 'Rarefaction is the reduction of an item''s density, the opposite of compression. Like compression, which can travel in waves (sound waves, for instance), rarefaction waves also exist in nature. Rarefaction waves expand with time (much like sea waves spread out as they reach a beach); in most cases rarefaction waves keep the same overall profile (''shape'') at all times throughout the wave''s movement: it is a self-similar expansion. Each part of the wave travels at the local speed of sound, in the local medium.', '2015-01-22 17:36:38'),
(10, 'Monera is a kingdom that contains unicellular organisms with a prokaryotic cell organization. the organisms found in kingdom Monera have been divided into two domains, Archaea and Bacteria (with Eukarya as the third domain). Furthermore the taxon Monera is paraphyletic (not all members descended from their most recent common ancestor), as Archaea andEukarya are currently believed to be more closely related than either is to Bacteria. ', '2015-01-22 18:01:55'),
(11, 'In cell biology, an organelle  is a specialized subunit within a cell that has a specific function. Individual organelles are usually separately enclosed within their own lipid bilayers. The name organelle comes from the idea that these structures are to cells what an organ is to the body.', '2015-01-22 18:01:55'),
(12, 'Cyanobacteria  also known as Cyanophyta, is a phylum of bacteria that obtain their energy through photosynthesis. The name "cyanobacteria" comes from the color of the bacteria .They are often called blue-green algae', '2015-01-22 18:01:55'),
(13, 'In some biological taxonomy schemes, protists  are a large and diverse group of eukaryotic microorganisms, which belong to the kingdom Protista.  They are unicellular, or they are multicellular without specialized tissues; this simple cellular organization distinguishes the protists from other eukaryotes, such as fungi, animals and plants, although some fungi and animals are also unicellular.', '2015-01-22 18:01:55'),
(14, 'A cilium (Latin for eyelash; the plural is cilia) is an organelle found in eukaryotic cells. Cilia are slender protuberances that project from the much larger cell body.', '2015-01-22 18:01:55'),
(15, 'A flagellum (plural: flagella) is a lash-like appendage that protrudes from the cell body of certain prokaryotic and eukaryotic cells. The word flagellum in Latin means whip. The primary role of the flagellum is locomotion but it also often has function as a sensory organelle, being sensitive to chemicals and temperatures outside the cell.', '2015-01-22 18:01:55'),
(16, 'A microorganism  is a microscopic living organism, which may be a single cell or a multicellular organism. Microorganisms are often referred to as microbes, but this is usually used in reference to pathogens.', '2015-01-22 18:01:55'),
(17, 'Tuberculosis, MTB, or TB (short for tubercle bacillus), in the past also called phthisis, phthisis pulmonalis, or consumption, is a widespread, and in many cases fatal, infectious disease caused by various strains of mycobacteria, usually Mycobacterium tuberculosis.  Tuberculosis typically attacks the lungs, but can also affect other parts of the body.', '2015-01-22 18:01:55'),
(18, 'Jaundice also known as icterus,  is a yellowish pigmentation of the skin, the conjunctival membranes over the sclerae (whites of the eyes), and other mucous membranes caused by high blood bilirubin levels', '2015-01-22 18:01:55'),
(19, 'A lymph node is an oval-shaped organ of the lymphatic system, distributed widely throughout the body including the armpit and stomach and linked by lymphatic vessels. Lymph nodes are major sites of B, T, and other immune cells. Lymph nodes are important for the proper functioning of the immune system, acting as filters for foreign particles and cancer cells. Lymph nodes do not deal with toxicity, which is primarily dealt with by the liver and kidneys.', '2015-01-22 18:01:55'),
(20, 'Malaria is a mosquito-borne infectious disease of humans and other animals caused by parasitic protozoans  (a type of single cell microorganism) of the Plasmodium type. Commonly, the disease is transmitted by the bite of an infected female Anopheles mosquito.', '2015-01-22 18:01:55'),
(21, 'Encephalitis is an acute inflammation of the brain. Symptoms include headache, fever, confusion, drowsiness, and fatigue.', '2015-01-22 18:01:55'),
(22, 'Fossil fuels are fuels formed by natural processes such as anaerobic decomposition of buried dead organisms. The age of the organisms and their resulting fossil fuels is typically millions of years, and sometimes exceeds 650 million years. Fossil fuels contain high percentages of carbon and include coal, petroleum, and natural gas.', '2015-01-22 18:01:55'),
(23, 'An oxide is a chemical compound that contains at least one oxygen atom and one other element  in its chemical formula. Metal oxides typically contain an anion of oxygen in the oxidation state of ?2.', '2015-01-22 18:01:55'),
(24, 'Acid rain is a rain or any other form of precipitation that is unusually acidic, meaning that it possesses elevated levels of hydrogen ions (low pH). It can have harmful effects on plants, aquatic animals and infrastructure. Acid rain is caused by emissions of sulfur dioxide and nitrogen oxide, which react with the water molecules in the atmosphere to produce acids.', '2015-01-22 18:01:55'),
(25, 'In organic chemistry, a hydrocarbon is an organic compound consisting entirely of hydrogen and carbon. The majority of hydrocarbons found on Earth naturally occur in crude oil, where decomposed organic matter provides an abundance of carbon and hydrogen which, when bonded, can catenate to form seemingly limitless chains', '2015-01-22 18:01:55'),
(26, 'Liquefied petroleum gas or liquid petroleum gas (LPG or LP gas), also referred to as simply propane or butane, are flammable mixtures of hydrocarbon gases used as fuel in heating appliances, cooking equipment, and vehicles.', '2015-01-22 18:01:55'),
(27, 'Compressed natural gas (CNG) (Methane stored at high pressure) can be used in place of gasoline (petrol), Diesel fuel and propane/LPG. CNG combustion produces fewer undesirable gases than the fuels mentioned above. It is safer than other fuels in the event of a spill, because natural gas is lighter than air and disperses quickly when released. CNG may be found above oil deposits, or may be collected from landfills or wastewater treatment plants where it is known as biogas.', '2015-01-22 18:01:55'),
(28, 'Volume is the quantity of three-dimensional space enclosed by some closed boundary, for example, the space that a substance (solid,liquid, gas, or plasma) or shape occupies or contains. Volume is often quantified numerically using the SI derived unit, the cubic metre. The volume of a container is generally understood to be the capacity of the container, i. e. the amount of fluid (gas or liquid) that the container could hold, rather than the amount of space the container itself displaces.', '2015-01-22 18:01:55'),
(29, 'Diffusion is the net movement of a substance (e.g., an atom, ion or molecule) from a region of high concentration to a region of low concentration.', '2015-01-22 18:01:55'),
(30, 'A colloid is a substance in which microscopically dispersed insoluble particles are suspended throughout another substance. Sometimes the dispersed substance alone is called the colloid.', '2015-01-22 18:01:55'),
(31, 'In chemistry, a suspension is a heterogeneous mixture containing solid particles that are sufficiently large for sedimentation.', '2015-01-22 18:01:55'),
(32, 'In Chemistry, a mixture is a material system made up of two or more different substances which are mixed but are not combined chemically. A mixture refers to the physical combination of two or more substances on which the identities are retained and are mixed in the form of solutions, suspensions, and colloids.', '2015-01-22 18:01:55'),
(33, 'In Chemistry, some mixtures are homogeneous. In other words, mixtures have the same proportions throughout a given sample or multiple samples of different proportion to create a consistent mixture.', '2015-01-22 18:01:55'),
(34, 'The Tyndall effect, also known as Tyndall scattering, is light scattering by particles in a colloid or particles in a fine suspension. Tyndall effect is seen when light-scattering particulate-matter is dispersed in an otherwise-light-transmitting medium.', '2015-01-22 18:01:55'),
(35, 'In plants, "parenchyma" is one of the three main types of ground tissue, and the commonest. Parenchyma cells make up the bulk of the soft parts of plants, including the insides of leaves, flowers and fruits.', '2015-01-22 18:01:55'),
(36, 'Chlorophyll (also chlorophyl) is a green pigment found in cyanobacteria and the chloroplasts of algae and plants. Its name is derived from the Greek words chloros ("green") and phyllon ("leaf"). Chlorophyll is an extremely important biomolecule, critical in photosynthesis, which allows plants to absorb energy from light. Chlorophyll absorbs light most strongly in the blue portion of the electromagnetic spectrum, followed by the red portion. Conversely, it is a poor absorber of green and near-green portions of the spectrum, hence the green color of chlorophyll-containing tissues.', '2015-01-22 18:01:55'),
(37, 'Photosynthesis is a process used by plants and other organisms to convert light energy, normally from the Sun, into chemical energy that can be later released to fuel the organisms'' activities. This chemical energy is stored in carbohydrate molecules, such as sugars, which are synthesized from carbon dioxide and water – hence the name photosynthesis', '2015-01-22 18:01:55'),
(38, 'In science, buoyancy is an upward force exerted by a fluid that opposes the weight of an immersed object. In a column of fluid, pressure increases with depth as a result of the weight of the overlying fluid. Thus a column of fluid, or an object submerged in the fluid, experiences greater pressure at the bottom of the column than at the top. This difference in pressure results in a net force that tends to accelerate an object upwards.', '2015-01-22 18:01:55'),
(39, 'Aerenchyma refers to spaces or air channels in the leaves, stems and roots of some plants, which allows exchange of gases between the shoot and the root.', '2015-01-22 18:01:55'),
(40, 'Collenchyma cells have thin primary walls with some areas of secondary thickening. Collenchyma provides extra structural support, particularly in regions of new growth.', '2015-01-22 18:02:45');

